name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Uploaden naar DirectAdmin
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Code ophalen
      uses: actions/checkout@v4
    
    - name: 📂 Bestanden versturen via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # BELANGRIJK: Dit is de map op je server waar de site moet staan.
        # Bij DirectAdmin is dit bijna altijd ./public_html/
        server-dir: ./node-app/
